/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConventionSchema {
  domain: string;
  content: AttributeDescription;
}
export interface AttributeDescription {
  propertyName: string;
  kind?: string;
  description: string;
  deprecated?: boolean;
  subAttributes?: {
    [k: string]: AttributeDescription;
  };
}
